### ISSUE TITLE
默认安装2.0，在PHP7环境下使用系统自带的例子增删改查报异常

### ISSUE THREAD

**Issue by joykerl** [phalapi/phalapi2#2]
在接口文档下调试返回结果如下，所有的接口都是这样，1.4版本没有这个问题：
200 OK
Date: Thu, 13 Jul 2017 09:00:09 GMT
Server: Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/7.1.2 mod_perl/2.0.8-dev Perl/v5.16.3
Connection: Keep-Alive
X-Powered-By: PHP/7.1.2
Content-Length: 1193
Keep-Alive: timeout=5, max=100
Content-Type: text/html; charset=UTF-8

"
\nFatal error:  Uncaught ArgumentCountError: Too few arguments to function PhalApi\\Helper\\Tracer::sql(), 0 passed in /Applications/XAMPP/xamppfiles/htdocs/phalApi2/vendor/phalapi/notorm/src/NotORM/Result.php on line 263 and exactly 1 expected in /Applications/XAMPP/xamppfiles/htdocs/phalApi2/vendor/phalapi/kernal/src/Helper/Tracer.php:92\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/phalApi2/vendor/phalapi/notorm/src/NotORM/Result.php(263): PhalApi\\Helper\\Tracer->sql()\n#1 /Applications/XAMPP/xamppfiles/htdocs/phalApi2/vendor/phalapi/notorm/src/NotORM/Result.php(812): NotORM_Result->query('SELECT * FROM p...', Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/phalApi2/vendor/phalapi/notorm/src/NotORM/Result.php(897): NotORM_Result->execute()\n#3 /Applications/XAMPP/xamppfiles/htdocs/phalApi2/src/app/Model/Examples/CURD.php(31): NotORM_Result->fetchAll()\n#4 /Applications/XAMPP/xamppfiles/htdocs/phalApi2/src/app/Domain/Examples/CURD.php(34): App\\Model\\Examples\\CURD->getListItems(0, 1, 10)\n#5 /Applications/XAMPP/xamppfiles/ in /Applications/XAMPP/xamppfiles/htdocs/phalApi2/vendor/phalapi/kernal/src/Helper/Tracer.php on line 92
\n"

**Comment by phalapi** [comment]
这个问题之前已经解决，拉取一下最新代码再试下？相关代码请见[Result.php](https://github.com/phalapi/notorm/blob/master/src/NotORM/Result.php) 第255行，对调试器的回调。  

上面263行已经是被修复的了，欢迎继续使用，谢谢。

**Comment by joykerl** [comment]
奇怪，我composer update 没解决。直接拷贝你贴的代码才解决

**Comment by phalapi** [comment]
可能是缓存。
